Presentation/Ardil.Web/Controllers/AuthController.cs
using Ardil.Application.Abstractions.Identity;
using Ardil.Application.Exceptions.IdentityExceptions;
using Ardil.Application.Helper.BaseClasses;
using Ardil.Domain.Entities.Identity;
using Ardil.Application.Models.IdentityModels.SignIn;
using Ardil.Application.Models.IdentityModels.SignUp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace Ardil.Web.Controllers
{
    public class AuthController : Controller
    {

        private readonly IAuthService _authService;

        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignIn(SignInRequestModel model)
        {
            try{
                var result = await _authService.SignInAsync(model);
                if (result.IsSuccess)
                {
                    HttpContext.Session.SetString("X-Access-Token", result.Token.AccessToken);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, result.Error);
                }
            }
            catch (UserNotFoundException e){
                ModelState.AddModelError("UserNotFoundError", e.Message);
                return View(model);
            }
            return RedirectToAction("Index","Home");
        }
        [AllowAnonymous]
        public IActionResult SignOut()
        {
            Response.Cookies.Delete("X-Access-Token");
            HttpContext.Session.Clear();
            HttpContext.SignOutAsync(JwtBearerDefaults.AuthenticationScheme);

            return RedirectToAction("SignIn", "Auth");
        }
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(SignUpRequestModel model)
        {
            try
            {
                var result = await _authService.SignUpAsync(model);
                if (result.IsSuccess)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    foreach (var error in result.ErrorMessages)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            catch (UserNotFoundException e)
            {
                ModelState.AddModelError("UserNotFoundError", e.Message);
            }
            return View(model);
        }
    }
}

Presentation/Ardil.Web/Controllers/HomeController.cs
using Ardil.Application.Abstractions;
using Ardil.Domain.Enums.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Ardil.Web.Controllers
{
    
    public class HomeController : Controller
    {
        private readonly IEntryService _entryService;

        public HomeController(IEntryService entryService)
        {
            _entryService = entryService;
        }



        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] string topicId)
        {
            if(topicId == null)
            {
                return View();
            }
            var entries = await _entryService.GetEntriesByTopicId(topicId);
            return View(entries);
        }
    }
}

Presentation/Ardil.Web/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ardil.Web.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Presentation/Ardil.Web/Controllers/TopicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ardil.Web.Controllers
{
    [Authorize(Roles = "Admin,Yazar")]
    public class TopicController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Presentation/Ardil.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Ardil.Web.Controllers
{
    [Authorize(Roles = "Admin,Çaylak,Yazar")]
    public class UserController : Controller
    {
        [HttpGet("/{userName}")]
        public IActionResult Index(string userName)
        {
            return View();
        }
    }
}

Presentation/Ardil.Web/ViewComponents/MenuTopicListViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Ardil.Web.ViewComponents
{
    public class MenuTopicListViewComponent: ViewComponent
    {


        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

Presentation/Ardil.Web/ViewComponents/PopularTopicsViewComponent.cs
using Ardil.Application.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace Ardil.Web.ViewComponents
{
    public class PopularTopicsViewComponent: ViewComponent
    {

        private readonly IEntryService _entryService;

        public PopularTopicsViewComponent(IEntryService entryService)
        {
            _entryService = entryService;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var topicalEntries = await _entryService.GetTopicalEntries();
            return View(topicalEntries);
        }
    }
}

Presentation/Ardil.Web/Views/Home/Index.cshtml
@model List<Ardil.Application.Models.EntryModels.EntryResponseModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Model != null)
{
    <h4 style="margin: 15px 0;font-size: 22px;color: #333333;"> <a href=""><b>@*_model.Topic.Subject*@</b></a>  </h4>
    foreach (var _model in Model)
    {
        <div style="padding: 2rem 0 2rem 0;">
            <p>@_model.Content</p>
            <div>
                <i class="fa-solid fa-circle-arrow-up"></i>
                <i class="fa-solid fa-circle-arrow-down" style="padding: 0 0 0 15px;"></i>
                <i class="fa-solid fa-ellipsis" style="float: right;padding: 0 10px 0 15px;"></i>
                <i class="fa-solid fa-arrow-up-from-bracket" style="float: right; "></i>
            </div>
            <div style=" display:flex ; float: right; font-size: 14px;" class="p-2">
                <div class="me-2 ">
                    <a style="display: block; text-align: right; text-decoration: none; color: #81C14B;" href="">@*_model.Entry.User.UserName*@</a>
                    <a style="display: block;text-decoration: none; color: #888888;" href="">@_model.CreatedDate</a>
                </div>
                <img src="img/user.svg" alt="">
            </div>
        </div>
    }
}
else
{
    @await Component.InvokeAsync("PopularTopics")
}

Presentation/Ardil.Web/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="/ample-admin/Login_v4/images/icons/favicon.ico" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/vendor/bootstrap/css/bootstrap.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/fonts/iconic/css/material-design-iconic-font.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/vendor/animate/animate.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/vendor/css-hamburgers/hamburgers.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/vendor/animsition/css/animsition.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/vendor/select2/select2.min.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/vendor/daterangepicker/daterangepicker.css">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/css/util.css">
	<link rel="stylesheet" type="text/css" href="/ample-admin/Login_v4/css/main.css">
	<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="limiter">
			<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
				<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
					@*<form class="login100-form validate-form">*@
						<form class="pt-3" method="post">
						<span class="login100-form-title p-b-49">
							Login
						</span>
						@*<div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">*@
						<div class="form-group">
							<span class="label-input100">Username</span>
							<input class="input100" type="text"  placeholder="Type your username">
							<span class="focus-input100" data-symbol="&#xf206;"></span>
						</div>
						@*<div class="wrap-input100 validate-input" data-validate="Password is required">*@
						<div class="form-group">
							<span class="label-input100">Password</span>
							<input class="input100" type="password" placeholder="Type your password">
							<span class="focus-input100" data-symbol="&#xf190;"></span>
						</div>
						<div class="container-login100-form-btn">
							<div class="wrap-login100-form-btn">
								<div class="login100-form-bgbtn"></div>
								<button class="login100-form-btn">
									Login
								</button>
							</div>
						</div>
						<div class="flex-col-c p-t-155">
							<span class="txt1 p-b-17">
								Or Sign Up Using
							</span>

							<a href="/Register/Index" class="txt2">
								Sign Up
							</a>
						</div>
				
					</form>
				</div>
			</div>
		</div>
	</div>

	
		<div id="dropDownSelect1"></div>

	<!--===============================================================================================-->
	<script src="/ample-admin/Login_v4/vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="/ample-admin/Login_v4/vendor/animsition/js/animsition.min.js"></script>
	<!--===============================================================================================-->
	<script src="/ample-admin/Login_v4/vendor/bootstrap/js/popper.js"></script>
	<script src="/ample-admin/Login_v4/vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="/ample-admin/Login_v4/vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="/ample-admin/Login_v4/vendor/daterangepicker/moment.min.js"></script>
	<script src="/ample-admin/Login_v4/vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
	<script src="/ample-admin/Login_v4/vendor/countdowntime/countdowntime.js"></script>
	<!--===============================================================================================-->
	<script src="/ample-admin/Login_v4/js/main.js"></script>

</body>
</html>

Presentation/Ardil.Web/Views/Post/CreatePost.cshtml
@{
    ViewData["Title"] = "CreatePost";
}

<h1>Post Girişi</h1>

<form method="post">

    <label>Mesaj</label>
<textarea cols="6" rows="8" class="form-control" ></textarea>
    <br />

    <button class="btn btn-primary">Paylaş</button>
</form>


      

Presentation/Ardil.Web/Views/Register/Index.cshtml
<link href="~/colorlib-regform-4/css/main.css" rel="stylesheet" />

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Au Register Forms by Colorlib</title>

    <!-- Icons font CSS-->
    <link href="/colorlib-regform-4/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="/colorlib-regform-4/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="/colorlib-regform-4/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="/colorlib-regform-4/vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="css/main.css" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">Registration Form</h2>
                    <form method="POST">
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">kullanıcı adı</label>
                                <input class="input--style-4" type="text" >
                                </div>                              
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Adınız</label>
                                    <input class="input--style-4" type="text" >
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Soyadınız</label>
                                    <input class="input--style-4" type="text" >
                                </div>
                            </div>
                             <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Parolanız</label>
                                    <input class="input--style-4" type="password" >
                                </div>
                            </div>
                        </div>
                       @* <div class="row row-space">
                           
                            
                        </div>*@
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Email</label>
                                    <input class="input--style-4" type="email">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Phone Number</label>
                                    <input class="input--style-4" type="text" >
                                </div>
                            </div>
                             
                        </div>
                        @*<div class="mt-3">
                            <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">Kayıt Ol</button>
                        </div>*@
                        <div class="p-t-15">
                            <button class="btn btn--radius-2 btn--blue" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="/colorlib-regform-4/vendor/jquery/jquery.min.js"></script>
    <!-- Vendor JS-->
    <script src="/colorlib-regform-4/vendor/select2/select2.min.js"></script>
    <script src="/colorlib-regform-4/vendor/datepicker/moment.min.js"></script>
    <script src="/colorlib-regform-4/vendor/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="js/global.js"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->
@*<form class="pt-3" method="post">
    <div class="form-group">
        <input type="text" class="form-control form-control-lg" id="exampleInputUsername1" placeholder="kullanıcı adınız" asp-for="UserName">
    </div>
    <div class="form-group">
        <input type="text" class="form-control form-control-lg" id="exampleInputUsername1" placeholder="adınız" asp-for="Name"> <!--burdaki name;asp.netuser tablosundaki name değil, AppUSer aracılığıyla kalıtım aldırdığım property AYRICA bunlar tek hepler a)item... yamzaya gerek kalmadan yukarıda tanıtılan modelin propertylerini direk algılıyor.-->
    </div>
    <div class="form-group">
        <input type="text" class="form-control form-control-lg" placeholder="soyadınız" asp-for="Surname">
    </div>
    <div class="form-group">
        <input type="email" class="form-control form-control-lg" id="exampleInputEmail1" placeholder="Email" asp-for="Email">
    </div>
    <div class="form-group">
        <input type="text" class="form-control form-control-lg" placeholder="Telefon Numaranız" asp-for="PhoneNumber">
    </div>
    <div class="form-group">
        <input type="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Şifreniz" asp-for="PasswordHash">
    </div>
    <div class="mb-4">
        <div class="form-check">
            <label class="form-check-label text-muted">
                <input type="checkbox" class="form-check-input">
                Kuralları okudum kabul ediyorum.
            </label>
        </div>
    </div>
    <div class="mt-3">
        <button class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">Kayıt Ol</button>
    </div>
    <div class="text-center mt-4 font-weight-light">
        Zaten bir hesabın var mı? <a href="/Login/Home/" class="text-primary">Giriş Yap</a>
    </div>
</form>*@



<!--ayse Asdfg12345*-->
<!--enes Asd123*-->

Presentation/Ardil.Web/Views/Shared/Components/MenuTopicList/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Presentation/Ardil.Web/Views/Shared/Components/PopularTopics/Default.cshtml
@model List<Ardil.Application.Models.EntryModels.TopicalEntriesResponseModel>

@foreach (var _model in Model)
{
    <div style="padding: 2rem 0 2rem 0;">
        <h4 style="margin: 15px 0;font-size: 22px;color: #333333;"> <a href="/?topicId=@_model.Topic.Id"><b>@_model.Topic.Subject</b></a>  </h4>
        <p>@_model.Entry.Content</p>
        <div>
            <i class="fa-solid fa-circle-arrow-up"></i>
            <i class="fa-solid fa-circle-arrow-down" style="padding: 0 0 0 15px;"></i>
            <i class="fa-solid fa-ellipsis" style="float: right;padding: 0 10px 0 15px;"></i>
            <i class="fa-solid fa-arrow-up-from-bracket" style="float: right; "></i>
        </div>
        <div style=" display:flex ; float: right; font-size: 14px;" class="p-2">
            <div class="me-2 ">
                <a style="display: block; text-align: right; text-decoration: none; color: #81C14B;" href="">@*_model.Entry.User.UserName*@</a>
                <a style="display: block;text-decoration: none; color: #888888;" href="">@_model.Entry.CreatedDate</a>
            </div>
            <img src="img/user.svg" alt="">
        </div>
    </div>
}

Presentation/Ardil.Web/Views/Update/Index.cshtml
<!--List olması için, birden fazla satıra ait veri dönmeliyiz.-->
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!DOCTYPE html>
<html dir="ltr" lang="en">

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Profili Güncelle</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                   @* <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal">Dashboard</a></li>
                    </ol>*@
                  @*  <a href="https://www.wrappixel.com/templates/ampleadmin/" target="_blank"
                       class="btn btn-danger  d-none d-md-block pull-right ms-3 hidden-xs hidden-sm waves-effect waves-light text-white">
                        Upgrade
                        to Pro
                    </a>*@
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-4 col-xlg-3 col-md-12">
                <div class="white-box">
                    <div class="user-bg">
                        <img width="100%" alt="user" src="~/UserImage/@Model.ImageURL">
                        <div class="overlay-box">
                            <div class="user-content">
                                <a href="javascript:void(0)">
                                    <img src="plugins/images/users/genu.jpg"
                                         class="thumb-lg img-circle" alt="img">
                                </a>
                                <h4 class="text-white mt-2">@Model.Name @Model.Surname</h4>
                              
                            </div>
                        </div>
                    </div>                  
                </div>
            </div>
            <!-- Column -->
            <!-- Column -->
            <div class="col-lg-8 col-xlg-9 col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form  method="post"class="form-horizontal form-material">
                            <div class="form-group mb-4">
                               @* <label class="col-md-12 p-0">Full Name</label>
                                <div class="col-md-12 border-bottom p-0">
                                    <input type="text" placeholder="Johnathan Doe"
                                           class="form-control p-0 border-0">
                                </div>*@
                                <label>Adınız:</label>
                                <input type="text"  class="form-control" />
                            </div>
                            <div class="form-group mb-4">
                               @* <label for="example-email" class="col-md-12 p-0">Email</label>
                                <div class="col-md-12 border-bottom p-0">
                                    <input type="email" placeholder="johnathan@admin.com"
                                           class="form-control p-0 border-0" name="example-email"
                                           id="example-email">
                                </div>*@
                                <label>Soyadınız:</label>
                                <input type="text"  class="form-control" />
                            </div>
                            <div class="form-group mb-4">
                               @* <label class="col-md-12 p-0">Password</label>
                                <div class="col-md-12 border-bottom p-0">
                                    <input type="password" value="password" class="form-control p-0 border-0">
                                </div>*@
                                <label>Email:</label>
                                <input type="email"  class="form-control" required />
                            </div>
                            <div class="form-group mb-4">
                              @*  <label class="col-md-12 p-0">Phone No</label>
                                <div class="col-md-12 border-bottom p-0">
                                    <input type="text" placeholder="123 456 7890"
                                           class="form-control p-0 border-0">
                                </div>*@
                                <label>Telefon Numarası:</label>
                                <input type="text"  class="form-control" />
                            </div>
                            <div class="form-group mb-4">
                                <label>Sifre:</label>
                                <input type="password" class="form-control" />
                                </div>
                            <div class="form-group mb-4">
                                <label>Şifre Tekrarı:</label>
                                <input type="password" class="form-control" />
                                </div>
                            <div class="form-group mb-4">
                                <label>Resim Seçiniz:</label>
                                <input type="file" class="form-control" />
                                </div>
                           
                            <div class="form-group mb-4">
                                <div class="col-sm-12">
                                    <button class="btn btn-success">Güncelle</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Column -->
        </div>
        <!-- Row -->
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
        2021 © Ample Admin brought to you by <a href="https://www.wrappixel.com/">wrappixel.com</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
<!-- ============================================================== -->
<!-- End Page wrapper  -->
<!-- ============================================================== -->
    </div>

</html>

Presentation/Ardil.Web/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Üye Listesi</h1>


<table class="table table-bordered">
    <tr>
        <th></th>
        <th>Adı Soyad</th>
        <th>Mail</th>
      @*  <th>Cinsiyet</th>
        <th>Sil</th>
        <th>Düzenle</th>
        <th>Detaylar</th>*@
    </tr>
    @*  @foreach (var item in Model) //burda model yazınca yukarıya list yazmak gerekli.
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name @item.Surname</td>
            <td>@item.Email</td>
            @*<td>@item.Gender</td>
            <td><a href="#" class="btn btn-outline-danger">Sil</a></td>
            <td><a href="#" class="btn btn-outline-success">Güncelle</a></td>
            <td><a href="#" class="btn btn-outline-dark">Detaylar</a></td>
        </tr>
    }*@
</table>
<a href="/Register/Index/" class="btn btn-primary me-2">Yeni Üye Kaydı</a>